baseURL = "https://wahyuwiyoko.github.io/blog/"
title = "Wahyu Wiyoko"
paginate = 5
disableLiveReload = true
pluralizeListTitles = false
enableGitInfo = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup.highlight]
noClasses = false
